# Dockerfile pour Ganache CLI
FROM node:16

RUN npm install -g ganache-cli

EXPOSE 8545

CMD ["ganache-cli", "-h", "0.0.0.0", "-p", "8545", "-i", "5777", "-m", "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat"]
